In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import pandas as pd 
import numpy as np
from numpy import linalg as LA
from scipy.linalg import lu
from scipy.linalg import lu_factor, lu_solve
from IPython.display import display, Math
from IPython.core import display as ICD

# Define function f(x,y)
def f(x, y):
    return np.exp(-(x**2+y**2))

# Define partial derivative of f(x,y) with regards to x
def fx(x, y):
    return -2*x*np.exp(-(x**2+y**2))

# Define partial derivative of f(x,y) with regards to y
def fy(x, y):
    return -2*y*np.exp(-(x**2+y**2))

# Define partial derivative of f_x(x,y) with regards to y
def fxy(x, y):
    return 4*x*y*np.exp(-(x**2+y**2))

# Define the function that take in coefficient matrix A, and return the polynomial p
def make_poly(A):
    # Define the polynomial p(x,y)
    def p(x, y):
        return (A[0] + A[1]*x + A[2]*x**2 + A[3]*x**3 + A[4]*y + A[5]*y**2 + A[6]*y**3 + 
                A[7]*x*y + A[8]*x**2*y + A[9]*x**3*y + A[10]*x*y**2 + A[11]*(x*y)**2 +
                A[12]*x**3*y**2 + A[13]*x*y**3 + A[14]*x**2*y**3 + A[15]*(x*y)**3)
    return p

def make_px(A):
    def px(x, y):
        return (A[1] + 2*A[2]*x + 3*A[3]*x**2 + A[7]*y + 2*A[8]*x*y + 3*A[9]*y*x**2 + A[10]*y**2 +
                2*A[11]*x*y**2 + 3*A[12]*x**2*y**2 + A[13]*y**3 + 2*A[14]*x*y**3 + 3*A[15]*x**2*y**3)
    return px

def make_pxy(A):
    def pxy(x, y):
        return (A[7] + 2*A[8]*x + 3*A[9]*x**2 + 2*A[10]*y +
                4*A[11]*x*y + 6*A[12]*x**2*y + 3*A[13]*y**2 + 6*A[14]*x*y**2 + 9*A[15]*x**2*y**2)
    return pxy

x = [0, 1, 0.5]

y = [0, 1, 0.5]



f1_values = np.array([ # Begin f values
            [f(x[0], y[0])],
            [f(x[1], y[0])],
            [f(x[0], y[1])],
            [f(x[1], y[1])],
            # End f values
            # Begin f_x values
            [fx(x[0], y[0])],
            [fx(x[1], y[0])],
            [fx(x[0], y[1])],
            [fx(x[1], y[1])],
            # End f_x values
            # Begin f_y values
            [fy(x[0], y[0])],
            [fy(x[1], y[0])],
            [fy(x[0], y[1])],
            [fy(x[1], y[1])],
            # End f_y values
            # Begin f_xy values
            [fxy(x[0], y[0])],
            [fxy(x[1], y[0])],
            [fxy(x[0], y[1])],
            [fxy(x[1], y[1])]
            # End f_xy values
            ])

f2_values = np.array([
            # Begin f values
            [f(x[0], y[0])],
            [f(x[1], y[0])],
            [f(x[0], y[1])],
            [f(x[1], y[1])],
            # End f values
            # Begin f_x values
            [fx(x[0], y[0])],
            [fx(x[1], y[0])],
            [fx(x[0], y[1])],
            [fx(x[1], y[1])],
            # End f_x values
            # Begin f_y values
            [fy(x[0], y[0])],
            [fy(x[1], y[0])],
            [fy(x[0], y[1])],
            [fy(x[1], y[1])],
            # End f_y values
            # Begin conditions
            [f(x[2], y[2])],
            [fx(x[2], y[2])],
            [fy(x[2], y[2])],
            [fxy(x[2], y[2])]
            # End conditions
            ])
    
B1 = np.array([ # Begin f section
     [1, x[0], x[0]**2, x[0]**3, y[0], y[0]**2, y[0]**3, x[0]*y[0], x[0]**2*y[0], x[0]**3*y[0], x[0]*y[0]**2, (x[0]*y[0])**2, x[0]**3*y[0]**2, x[0]*y[0]**3, x[0]**2*y[0]**3, (x[0]*y[0])**3],
     [1, x[1], x[1]**2, x[1]**3, y[0], y[0]**2, y[0]**3, x[1]*y[0], x[1]**2*y[0], x[1]**3*y[0], x[1]*y[0]**2, (x[1]*y[0])**2, x[1]**3*y[0]**2, x[1]*y[0]**3, x[1]**2*y[0]**3, (x[1]*y[0])**3],
     [1, x[0], x[0]**2, x[0]**3, y[1], y[1]**2, y[1]**3, x[0]*y[1], x[0]**2*y[1], x[0]**3*y[1], x[0]*y[1]**2, (x[0]*y[1])**2, x[0]**3*y[1]**2, x[0]*y[1]**3, x[0]**2*y[1]**3, (x[0]*y[1])**3],
     [1, x[1], x[1]**2, x[1]**3, y[1], y[1]**2, y[1]**3, x[1]*y[1], x[1]**2*y[1], x[1]**3*y[1], x[1]*y[1]**2, (x[1]*y[1])**2, x[1]**3*y[1]**2, x[1]*y[1]**3, x[1]**2*y[1]**3, (x[1]*y[1])**3],
     # End f section
     # Begin f_x section
     [0, 1, 2*x[0], 3*x[0]**2, 0, 0, 0, y[0], 2*x[0]*y[0], 3*x[0]**2*y[0], y[0]**2, 2*x[0]*y[0]**2, 3*(x[0]*y[0])**2, y[0]**3, 2*x[0]*y[0]**3, 3*x[0]**2*y[0]**3],
     [0, 1, 2*x[1], 3*x[1]**2, 0, 0, 0, y[0], 2*x[1]*y[0], 3*x[1]**2*y[0], y[0]**2, 2*x[1]*y[0]**2, 3*(x[1]*y[0])**2, y[0]**3, 2*x[1]*y[0]**3, 3*x[1]**2*y[0]**3],
     [0, 1, 2*x[0], 3*x[0]**2, 0, 0, 0, y[1], 2*x[0]*y[1], 3*x[0]**2*y[1], y[1]**2, 2*x[0]*y[1]**2, 3*(x[0]*y[1])**2, y[1]**3, 2*x[0]*y[1]**3, 3*x[0]**2*y[1]**3],
     [0, 1, 2*x[1], 3*x[1]**2, 0, 0, 0, y[1], 2*x[1]*y[1], 3*x[1]**2*y[1], y[1]**2, 2*x[1]*y[1]**2, 3*(x[1]*y[1])**2, y[1]**3, 2*x[1]*y[1]**3, 3*x[1]**2*y[1]**3],
     # End f_x section
     # Begin f_y section
     [0, 0, 0, 0, 1, 2*y[0], 3*y[0]**2, x[0], x[0]**2, x[0]**3, 2*x[0]*y[0], 2*x[0]**2*y[0], 2*x[0]**3*y[0], 3*x[0]*y[0]**2, 3*(x[0]*y[0])**2, 3*x[0]**3*y[0]**2],
     [0, 0, 0, 0, 1, 2*y[0], 3*y[0]**2, x[1], x[1]**2, x[1]**3, 2*x[1]*y[0], 2*x[1]**2*y[0], 2*x[1]**3*y[0], 3*x[1]*y[0]**2, 3*(x[1]*y[0])**2, 3*x[1]**3*y[0]**2],
     [0, 0, 0, 0, 1, 2*y[1], 3*y[1]**2, x[0], x[0]**2, x[0]**3, 2*x[0]*y[1], 2*x[0]**2*y[1], 2*x[0]**3*y[1], 3*x[0]*y[1]**2, 3*(x[0]*y[1])**2, 3*x[0]**3*y[1]**2],
     [0, 0, 0, 0, 1, 2*y[1], 3*y[1]**2, x[1], x[1]**2, x[1]**3, 2*x[1]*y[1], 2*x[1]**2*y[1], 2*x[1]**3*y[1], 3*x[1]*y[1]**2, 3*(x[1]*y[1])**2, 3*x[1]**3*y[1]**2],
     # End f_y section
     # Begin f_xy section
     [0, 0, 0, 0, 0, 0, 0, 1, 2*x[0], 3*x[0]**2, 2*y[0], 4*x[0]*y[0], 6*x[0]**2*y[0], 3*y[0]**2, 6*x[0]*y[0]**2, 9*(x[0]*y[0])**2],
     [0, 0, 0, 0, 0, 0, 0, 1, 2*x[1], 3*x[1]**2, 2*y[0], 4*x[1]*y[0], 6*x[1]**2*y[0], 3*y[0]**2, 6*x[1]*y[0]**2, 9*(x[1]*y[0])**2],
     [0, 0, 0, 0, 0, 0, 0, 1, 2*x[0], 3*x[0]**2, 2*y[1], 4*x[0]*y[1], 6*x[0]**2*y[1], 3*y[1]**2, 6*x[0]*y[1]**2, 9*(x[0]*y[1])**2],
     [0, 0, 0, 0, 0, 0, 0, 1, 2*x[1], 3*x[1]**2, 2*y[1], 4*x[1]*y[1], 6*x[1]**2*y[1], 3*y[1]**2, 6*x[1]*y[1]**2, 9*(x[1]*y[1])**2]
     # End f_xy section
     ])

    
B2 = np.array([ # Begin f section
     [1, x[0], x[0]**2, x[0]**3, y[0], y[0]**2, y[0]**3, x[0]*y[0], x[0]**2*y[0], x[0]**3*y[0], x[0]*y[0]**2, (x[0]*y[0])**2, x[0]**3*y[0]**2, x[0]*y[0]**3, x[0]**2*y[0]**3, (x[0]*y[0])**3],
     [1, x[1], x[1]**2, x[1]**3, y[0], y[0]**2, y[0]**3, x[1]*y[0], x[1]**2*y[0], x[1]**3*y[0], x[1]*y[0]**2, (x[1]*y[0])**2, x[1]**3*y[0]**2, x[1]*y[0]**3, x[1]**2*y[0]**3, (x[1]*y[0])**3],
     [1, x[0], x[0]**2, x[0]**3, y[1], y[1]**2, y[1]**3, x[0]*y[1], x[0]**2*y[1], x[0]**3*y[1], x[0]*y[1]**2, (x[0]*y[1])**2, x[0]**3*y[1]**2, x[0]*y[1]**3, x[0]**2*y[1]**3, (x[0]*y[1])**3],
     [1, x[1], x[1]**2, x[1]**3, y[1], y[1]**2, y[1]**3, x[1]*y[1], x[1]**2*y[1], x[1]**3*y[1], x[1]*y[1]**2, (x[1]*y[1])**2, x[1]**3*y[1]**2, x[1]*y[1]**3, x[1]**2*y[1]**3, (x[1]*y[1])**3],
     # End f section
     # Begin f_x section
     [0, 1, 2*x[0], 3*x[0]**2, 0, 0, 0, y[0], 2*x[0]*y[0], 3*x[0]**2*y[0], y[0]**2, 2*x[0]*y[0]**2, 3*(x[0]*y[0])**2, y[0]**3, 2*x[0]*y[0]**3, 3*x[0]**2*y[0]**3],
     [0, 1, 2*x[1], 3*x[1]**2, 0, 0, 0, y[0], 2*x[1]*y[0], 3*x[1]**2*y[0], y[0]**2, 2*x[1]*y[0]**2, 3*(x[1]*y[0])**2, y[0]**3, 2*x[1]*y[0]**3, 3*x[1]**2*y[0]**3],
     [0, 1, 2*x[0], 3*x[0]**2, 0, 0, 0, y[1], 2*x[0]*y[1], 3*x[0]**2*y[1], y[1]**2, 2*x[0]*y[1]**2, 3*(x[0]*y[1])**2, y[1]**3, 2*x[0]*y[1]**3, 3*x[0]**2*y[1]**3],
     [0, 1, 2*x[1], 3*x[1]**2, 0, 0, 0, y[1], 2*x[1]*y[1], 3*x[1]**2*y[1], y[1]**2, 2*x[1]*y[1]**2, 3*(x[1]*y[1])**2, y[1]**3, 2*x[1]*y[1]**3, 3*x[1]**2*y[1]**3],
     # End f_x section
     # Begin f_y section
     [0, 0, 0, 0, 1, 2*y[0], 3*y[0]**2, x[0], x[0]**2, x[0]**3, 2*x[0]*y[0], 2*x[0]**2*y[0], 2*x[0]**3*y[0], 3*x[0]*y[0]**2, 3*(x[0]*y[0])**2, 3*x[0]**3*y[0]**2],
     [0, 0, 0, 0, 1, 2*y[0], 3*y[0]**2, x[1], x[1]**2, x[1]**3, 2*x[1]*y[0], 2*x[1]**2*y[0], 2*x[1]**3*y[0], 3*x[1]*y[0]**2, 3*(x[1]*y[0])**2, 3*x[1]**3*y[0]**2],
     [0, 0, 0, 0, 1, 2*y[1], 3*y[1]**2, x[0], x[0]**2, x[0]**3, 2*x[0]*y[1], 2*x[0]**2*y[1], 2*x[0]**3*y[1], 3*x[0]*y[1]**2, 3*(x[0]*y[1])**2, 3*x[0]**3*y[1]**2],
     [0, 0, 0, 0, 1, 2*y[1], 3*y[1]**2, x[1], x[1]**2, x[1]**3, 2*x[1]*y[1], 2*x[1]**2*y[1], 2*x[1]**3*y[1], 3*x[1]*y[1]**2, 3*(x[1]*y[1])**2, 3*x[1]**3*y[1]**2],
     # End f_y section
     # Begin conditions
     [1, x[2], x[2]**2, x[2]**3, y[2], y[2]**2, y[2]**3, x[2]*y[2], x[2]**2*y[2], x[2]**3*y[2], x[2]*y[2]**2, (x[2]*y[2])**2, x[2]**3*y[2]**2, x[2]*y[2]**3, x[2]**2*y[2]**3, (x[2]*y[2])**3],
     [0, 1, 2*x[2], 3*x[2]**2, 0, 0, 0, y[2], 2*x[2]*y[2], 3*x[2]**2*y[2], y[2]**2, 2*x[2]*y[2]**2, 3*(x[2]*y[2])**2, y[2]**3, 2*x[2]*y[2]**3, 3*x[2]**2*y[2]**3],
     [0, 0, 0, 0, 1, 2*y[2], 3*y[2]**2, x[2], x[2]**2, x[2]**3, 2*x[2]*y[2], 2*x[2]**2*y[2], 2*x[2]**3*y[2], 3*x[2]*y[2]**2, 3*(x[2]*y[2])**2, 3*x[2]**3*y[2]**2],
     [0, 0, 0, 0, 0, 0, 0, 1, 2*x[2], 3*x[2]**2, 2*y[2], 4*x[2]*y[2], 6*x[2]**2*y[2], 3*y[2]**2, 6*x[2]*y[2]**2, 9*(x[2]*y[2])**2]
     # End conditions
     ])

points = np.array([[0.25, 0.25], [0.4, 0.8], [0.75, 0.25], [0.8, 0.9]])

# LU-Factorize matrix B1 into LU and pivot
lu1, piv1 = lu_factor(B1) 
# Solve an equation given the LU factorization
alpha1 = lu_solve((lu1, piv1), f1_values)

# Report the estimated results for the values of f, f_x, f_xy when solving f = e^-(x^2+y^2)
# Display f values
f1_df = pd.DataFrame(f1_values)
f1_df.index +=1
f1_df.columns = ["$f_{1}$"]
display(Math(r"f(x,y) = e^{-(x^2+y^2)}"))
ICD.display(f1_df)

# Display alpha values
a1_df = pd.DataFrame(alpha1)
a1_df.index = ['$a_{00}$','$a_{10}$','$a_{20}$','$a_{30}$','$a_{01}$','$a_{02}$','$a_{03}$','$a_{11}$','$a_{21}$','$a_{31}$','$a_{12}$','$a_{22}$','$a_{32}$','$a_{13}$','$a_{23}$','$a_{33}$']
a1_df.columns = ['α1']
ICD.display(a1_df)

#Display the values of p, p_x, p_xy
p1 = make_poly(alpha1)
px1 = make_px(alpha1)
pxy1 = make_pxy(alpha1)

# Calculate the errors for f, f_x, f_xy estimations
appx_f1 = np.array([p1(v[0], v[1]) for v in points])
error_f1 = np.array([abs(f(v[0], v[1]) - p1(v[0], v[1])) for v in points])
appx_fx1 = np.array([px1(v[0], v[1]) for v in points])
error_fx1 = np.array([abs(fx(v[0], v[1]) - px1(v[0], v[1])) for v in points])
appx_fxy1 = np.array([pxy1(v[0], v[1]) for v in points])
error_fxy1 = np.array([abs(fxy(v[0], v[1]) - pxy1(v[0], v[1])) for v in points])

# Display the errors 
appx_df1 = pd.DataFrame.from_dict({
    '$x$': points[:,0],
    '$y$': points[:,1],
    '$\hat{f}$': appx_f1.squeeze(),
    'error $\hat{f}$' : error_f1.squeeze(),
    '$\hat{f}_x$': appx_fx1.squeeze(),
    'error $\hat{f}_{x}$' : error_fx1.squeeze(),
    '$\hat{f}_{xy}$': appx_fxy1.squeeze(),
    'error $\hat{f}_{xy}$' : error_fxy1.squeeze()
})
ICD.display(appx_df1)

# Calculate and display the 1-norm and 2-norm errors for f, f_x, f_xy estimations
norm_df1 = pd.DataFrame(
    [(LA.norm(error_f1, ord = 1), LA.norm(error_f1, ord = 2)),
      (LA.norm(error_fx1, ord = 1), LA.norm(error_fx1, ord = 2)),
       (LA.norm(error_fxy1, ord = 1), LA.norm(error_fxy1, ord = 2))],
    index = ['$f$','$f_{x}$', '$f_{xy}$'],
    columns = ['1-norm', '2-norm']  
)
ICD.display(norm_df1)

# LU-Factorize matrix B2 into LU and pivot
lu2, piv2 = lu_factor(B2)
# Solve an equation given the LU factorization
alpha2 = lu_solve((lu2, piv2), f2_values)

# Report the estimated results for the values of f, f_x, f_xy when solving f = tanh(xy)
# Display f values
f2_df = pd.DataFrame(f2_values)
f2_df.index +=1
f2_df.columns = ["$f_2$"]
display(Math(r"f(x,y) = e^{-(x^2+y^2)}"))
ICD.display(f2_df)

# Display alpha values
a2_df = pd.DataFrame(alpha2)
a2_df.index = ['$a_{00}$','$a_{10}$','$a_{20}$','$a_{30}$','$a_{01}$','$a_{02}$','$a_{03}$','$a_{11}$','$a_{21}$','$a_{31}$','$a_{12}$','$a_{22}$','$a_{32}$','$a_{13}$','$a_{23}$','$a_{33}$']
a2_df.columns = ['α2']
ICD.display(a2_df)

#Display the estimations for p, p_x, p_xy
p2 = make_poly(alpha2)
px2 = make_px(alpha2)
pxy2 = make_pxy(alpha2)

# Calculate the errors for f, f_x, f_xy estimations
appx_f2 = np.array([p2(v[0], v[1]) for v in points])
error_f2 = np.array([abs(f(v[0], v[1]) - p2(v[0], v[1])) for v in points])
appx_fx2 = np.array([px2(v[0], v[1]) for v in points])
error_fx2 = np.array([abs(fx(v[0], v[1]) - px2(v[0], v[1])) for v in points])
appx_fxy2 = np.array([pxy2(v[0], v[1]) for v in points])
error_fxy2 = np.array([abs(fxy(v[0], v[1]) - pxy2(v[0], v[1])) for v in points])

# Display the errors 
appx_df2 = pd.DataFrame.from_dict({
    '$x$': points[:,0],
    '$y$': points[:,1],
    '$\hat{f}$': appx_f2.squeeze(),
    'error $\hat{f}$' : error_f2.squeeze(),
    '$\hat{f}_x$': appx_fx2.squeeze(),
    'error $\hat{f}_{x}$' : error_fx2.squeeze(),
    '$\hat{f}_{xy}$': appx_fxy2.squeeze(),
    'error $\hat{f}_{xy}$' : error_fxy2.squeeze()
})
ICD.display(appx_df2)

# Calculate and display the 1-norm and 2-norm errors for f, f_x, f_xy estimations
norm_df2 = pd.DataFrame(
    [(LA.norm(error_f2, ord = 1), LA.norm(error_f2, ord = 2)),
      (LA.norm(error_fx2, ord = 1), LA.norm(error_fx2, ord = 2)),
       (LA.norm(error_fxy2, ord = 1), LA.norm(error_fxy2, ord = 2))],
    index = ['$f$','$f_{x}$', '$f_{xy}$'],
    columns = ['1-norm', '2-norm'])
ICD.display(norm_df2)

     $f_{1}$
1   1.000000
2   0.367879
3   0.367879
4   0.135335
5   0.000000
6  -0.735759
7   0.000000
8  -0.270671
9   0.000000
10  0.000000
11 -0.735759
12 -0.270671
13  0.000000
14  0.000000
15  0.000000
16  0.541341

                α1
$a_{00}$  1.000000
$a_{10}$  0.000000
$a_{20}$ -1.160603
$a_{30}$  0.528482
$a_{01}$  0.000000
$a_{02}$ -1.160603
$a_{03}$  0.528482
$a_{11}$  0.000000
$a_{21}$ -0.000000
$a_{31}$ -0.000000
$a_{12}$  0.000000
$a_{22}$  1.346999
$a_{32}$ -0.613358
$a_{13}$  0.000000
$a_{23}$ -0.613358
$a_{33}$  0.279293

,$x$,$y$,$\hat{f}$,error $\hat{f}$,$\hat{f}_x$,error $\hat{f}_{x}$,$\hat{f}_{xy}$,error $\hat{f}_{xy}$
0,0.25,0.25,0.875572,0.006925,-0.450279,0.009030,0.231564,0.010940
1,0.40,0.80,0.447639,0.001690,-0.356163,0.003300,0.568379,0.006762
2,0.75,0.25,0.533467,0.001794,-0.794511,0.008381,0.408592,0.007146
3,0.80,0.90,0.234962,0.000392,-0.374962,0.000351,0.677927,0.002365

            1-norm    2-norm
$f$       0.010802  0.007361
$f_{x}$   0.021062  0.012760
$f_{xy}$  0.027213  0.014902

       $f_2$
1   1.000000
2   0.367879
3   0.367879
4   0.135335
5   0.000000
6  -0.735759
7   0.000000
8  -0.270671
9   0.000000
10  0.000000
11 -0.735759
12 -0.270671
13  0.606531
14 -0.606531
15 -0.606531
16  0.606531

                α2
$a_{00}$  1.000000
$a_{10}$  0.000000
$a_{20}$ -1.160603
$a_{30}$  0.528482
$a_{01}$  0.000000
$a_{02}$ -1.160603
$a_{03}$  0.528482
$a_{11}$  0.378563
$a_{21}$ -0.775071
$a_{31}$  0.396508
$a_{12}$ -0.775071
$a_{22}$  2.878036
$a_{32}$ -1.369325
$a_{13}$  0.396508
$a_{23}$ -1.369325
$a_{33}$  0.638752

,$x$,$y$,$\hat{f}$,error $\hat{f}$,$\hat{f}_x$,error $\hat{f}_{x}$,$\hat{f}_{xy}$,error $\hat{f}_{xy}$
0,0.25,0.25,0.882700,0.000204,-0.442049,0.000800,0.237399,0.016775
1,0.40,0.80,0.448321,0.001008,-0.359778,0.000314,0.587649,0.012507
2,0.75,0.25,0.535206,0.000055,-0.809927,0.007035,0.392016,0.009430
3,0.80,0.90,0.234434,0.000136,-0.374031,0.001281,0.680719,0.005156

            1-norm    2-norm
$f$       0.001403  0.001038
$f_{x}$   0.009431  0.007203
$f_{xy}$  0.043869  0.023524